feat: show injected options in wallet browsers
Uniswap/interface pull request #3995
Opened 2022-06-29 04:19 UTC by vm

.

2022-06-29 15:44 UTC, JFrankfurt commented
It seems like we've had a lot of inconsistent behavior around these options rendering correctly. Can you write a test for this that makes assertions on which options should be rendering in certain contexts?

2022-06-29 15:49 UTC, JFrankfurt requested changes
It seems like we've had a lot of inconsistent behavior around these options rendering correctly. Can you write a test for this that makes assertions on which options should be rendering in certain contexts?

2022-06-30 16:15 UTC, lynnshaoyu approved these changes
LGTM over all. Approved, just pls change the tests naming before submit. Ty

2022-06-30 16:15 UTC, lynnshaoyu commented on src/components/WalletModal/index.test.tsx
> +test('Loads Wallet Modal on MetaMask browser', async () => {
Can we change these test names to things like "it('loads wallet modal on MetaMask browser'....". The 'it' is an alias for test and its supposed to be a naming convention like "it ... is supposed to behave like this". 
All the other tests in the repo use 'it' currently so just want to keep it consistent.

2022-06-30 16:26 UTC, merged