chore: updates web3-react, adds key for changing connector order
Uniswap/interface pull request #4085
Opened 2022-07-12 15:53 UTC by vm

Latest version of web3-react requires the implementor to provider a key when the connectors array changes.

We change the connectors array when we prioritize the currently selected wallet's connector above others. The alternative option would be to use the prop `connectorOverride`, but this would break usage of `gnosisSafe` as that must come first.

I'm open minded on a different way to create this key, and also whether we should memoize it as it's near the top of the heirarchy.

2022-07-12 17:10 UTC, zzmp requested changes
I'm unsure why the code changes are necessary. Can they be backed out?

The package.json looks good but the new lockfile needs to be de-duped.

2022-07-12 17:10 UTC, zzmp commented on src/hooks/useOrderedConnections.ts
> +    return orderedConnectionTypes.map(getConnection)
I preferred the add'l mapping in here. Why did you move it?

2022-07-12 17:10 UTC, zzmp commented on src/connection/utils.ts
> +export function getConnectionName(connectionType: ConnectionType, isMetaMask?: boolean) {
If this is just for keys, is it still necessary?

2022-07-12 17:10 UTC, zzmp commented on yarn.lock
> +"@ethersproject/networks@5.6.4":
can be deduped with above entry.

2022-07-13 19:38 UTC, NoahZinsmeister approved these changes
lgtm

2022-07-13 19:44 UTC, merged