feat: plug in query data into token details
Uniswap/interface pull request #4331
Opened 2022-08-11 18:57 UTC by kayleegeorge

plug in query data into token details

2022-08-11 18:59 UTC, kayleegeorge commented on src/components/Explore/TokenDetails/TokenDetail.tsx
> +const tokenDetailsStatsQuery = gql`
query @cartcrom

2022-08-11 20:42 UTC, cartcrom requested changes

2022-08-11 20:42 UTC, cartcrom commented on src/components/Explore/TokenDetails/TokenDetail.tsx
> +import { CHAIN_SUBGRAPH_URL } from 'state/data/slice'
The current graphql URLs in redux are for querying a separate set of data specific to Pools, it has no use here. Relay hook calls with automatically use the correct url once that's setup, so no need to worry about urls here

2022-08-11 20:42 UTC, cartcrom commented on src/components/Explore/TokenDetails/TokenDetail.tsx
> +      chain: token ? CHAIN_SUBGRAPH_URL[token.chainId] : CHAIN_SUBGRAPH_URL[SupportedChainId.MAINNET],
I believe chain here should just be the the token's chain id, not a url

2022-08-11 20:42 UTC, cartcrom commented on src/state/data/slice.ts
> +export const CHAIN_SUBGRAPH_URL: Record<number, string> = {
undo all changes in this file since this url isn't needed elsewhere

2022-08-18 20:12 UTC, cmcewen commented on src/components/Tokens/TokenDetails/TokenDetail.tsx
> +      chain: token ? token.chainId : SupportedChainId.MAINNET,
i'm not sure falling back to mainnet is right here - imo the address + chainId go together as a unit, and in the worst case we would show the wrong token on a different network

2022-08-18 20:12 UTC, cmcewen commented on src/components/Tokens/TokenDetails/TokenDetail.tsx
> +              {!token ? 'No token name available' : token.name} <TokenSymbol>{token && token.symbol}</TokenSymbol>
i18n this?

2022-08-18 22:20 UTC, kayleegeorge commented
closing this for: https://github.com/Uniswap/interface/pull/4407 and will integrate query in another PR

2022-08-18 22:20 UTC, closed without merging