feat: add L2 network label to Explore token row
Uniswap/interface pull request #4361
Opened 2022-08-15 19:59 UTC by kayleegeorge

Add L2 network badge to token rows on Explore based on network filter dropdown

<img width="556" alt="Screen Shot 2022-08-15 at 12 44 14 PM" src="https://user-images.githubusercontent.com/62825936/184708325-53d5c159-956b-4c47-a811-27144377f07d.png">

2022-08-16 22:01 UTC, vm reviewed
should this live in chaininfo?

2022-08-16 22:08 UTC, kayleegeorge commented
> should this live in chaininfo?

normally I'd say yes, but this is like a 'secondary logo'? so wasn't sure -- there's a different logo that is used for the network switcher for example

2022-08-17 02:13 UTC, vm requested changes
Rename `Arbitrum.png` to `arbitrumCircle.png` (and for other chains)
Rename `arbitrumSecondaryLogoUrl` to `arbitrumCircleLogoUrl`

2022-08-17 21:35 UTC, vm approved these changes

2022-08-17 21:35 UTC, merged