fix: time selector updated to align with price chart
Uniswap/interface pull request #4425
Opened 2022-08-19 23:09 UTC by kayleegeorge

fix time selector on Explore page to be accurate and also use PriceChart logic

Before: 
<img width="423" alt="Screen Shot 2022-08-19 at 4 08 42 PM" src="https://user-images.githubusercontent.com/62825936/185717940-973434ba-2b3c-46a5-99a8-8bee81e916f6.png">

After:
<img width="613" alt="Screen Shot 2022-08-19 at 4 07 49 PM" src="https://user-images.githubusercontent.com/62825936/185717908-71669a39-4579-4038-a36d-72ad2d57f0f1.png">

2022-08-19 23:37 UTC, vm commented on src/components/Tokens/TokenDetails/PriceChart.tsx
> +export const TIME_DISPLAYS: [TimePeriod, string][] = [
this really shouldn't be an array?

2022-08-19 23:38 UTC, vm commented on src/components/Tokens/TokenDetails/PriceChart.tsx
> +export const TIME_DISPLAYS: [TimePeriod, string][] = [
there should `displays: Record<TimePeriod, string`, `orderedDisplays: TimePeriod[]`, and `TimePeriod`

2022-08-19 23:39 UTC, vm requested changes
.

2022-08-22 16:34 UTC, lynnshaoyu approved these changes

2022-08-22 16:37 UTC, vm approved these changes

2022-08-22 16:37 UTC, merged