Fix: added eth to explore
Uniswap/interface pull request #4517
Opened 2022-08-26 19:30 UTC by cartcrom

Might need to change later depending on whether we have wETH and ETH separate

2022-08-30 20:24 UTC, aballerr commented
> Might need to change later depending on whether we have wETH and ETH separate

I would create a task in jira or a todo comment if this is important to make sure we account for this somewhere

2022-08-30 23:57 UTC, zzmp requested changes

2022-08-30 23:57 UTC, zzmp commented on src/graphql/data/TopTokenQuery.ts
> +    let address = token?.tokens?.[0].address
Can this instead be compared to existing constants? See src/constants/tokens.ts specifically nativeOnChain (note you can also get this as a hook through useNativeCurrency).

You can probably compare this with ExtendedEther.onChain(chain) to make it more cross-chain compatible.

2022-10-18 16:22 UTC, vm commented
This is close-able now?

2022-10-18 16:25 UTC, closed without merging