fix: swap hover states
Uniswap/interface pull request #4771
Opened 2022-09-30 16:54 UTC by vm

2022-09-30 17:29 UTC, vm commented on src/components/swap/SwapDetailsDropdown.tsx
> +  margin-top: 4px !important;
rm

2022-10-04 16:35 UTC, zzmp approved these changes
lgtm, a few minor questions

2022-10-04 16:35 UTC, zzmp commented on src/components/swap/SwapDetailsDropdown.tsx
> +  padding: ${({ redesignFlag }) => (redesignFlag ? 'none' : '4px 8px')};
nit: I prefer `0` over `none`.

2022-10-04 16:35 UTC, zzmp commented on src/components/swap/SwapDetailsDropdown.tsx
> +    <Wrapper style={{ marginTop: '0px' }} redesignFlag={redesignFlagEnabled}>
Does this need to retain a `marginTop` without `redesignFlagEnabled`?

2022-10-04 16:35 UTC, zzmp commented on src/pages/Swap/index.tsx
> +  const showPriceImpactWarning = largerPriceImpact && priceImpactTooHigh
This will no longer show the impact warning in expert mode. Is this intended?

2022-10-04 16:37 UTC, zzmp reviewed
There's something slowing down rendering on hover - I'm looking into the preview rn

2022-10-04 16:41 UTC, zzmp requested changes
Hovering over the swap-arrows button makes it transparent, and shows the outline of the button below it. There should be an opaque box underneath the button to prevent this leak-through.

2022-10-04 16:51 UTC, vm commented
1) The hover issue is present on prod as well. I reverted the arrow changes (other than an alignment fix) and will copy what is in widget over to fix.
2) Checked the design and the reverse button goes over the border.

2022-10-04 18:09 UTC, zzmp approved these changes

2022-10-04 18:10 UTC, merged