refactor: initial push
Uniswap/interface pull request #4948
Opened 2022-10-17 21:18 UTC by cartcrom

Reduced size of TokenRow.tsx by rewriting parts and breaking out into modules

2022-10-25 03:04 UTC, zzmp requested changes

2022-10-25 03:04 UTC, zzmp commented on src/components/Tokens/TokenTable/TokenRow/index.tsx
> +      <PriceCell>
Why does `PriceCell` no longer have children?

2022-10-25 03:04 UTC, zzmp commented on src/components/Tokens/TokenTable/TokenRow/index.tsx
> +        volume={formatDollar({ num: token.market?.volume?.value })}
Is this no longer clickable? Or has that been moved to TokenRowCells? Same with above.

2022-10-25 03:04 UTC, zzmp commented on src/components/Tokens/TokenTable/TokenTable.tsx
> +const LoadingRowsWrapper = styled.div`
Is this new?

2023-04-05 04:31 UTC, tinaszheng commented
@cartcrom are you still working on this? if not can you close 🤔

2023-05-01 15:28 UTC, closed without merging