chore: remove redesign flag in base shared components
Uniswap/interface pull request #4958
Opened 2022-10-18 15:54 UTC by vm

one piece of removing the redesign flag within the codebase

2022-10-18 17:05 UTC, vm commented
depends on https://github.com/Uniswap/interface/pull/4959

2022-10-24 19:50 UTC, zzmp requested changes

2022-10-24 19:50 UTC, zzmp commented on src/components/SearchModal/CommonBases.tsx
> +    background-color: ${({ theme, disable }) => theme.hoverDefault || (!disable && theme.deprecated_bg2)};
This will never be triggered - should it just be hoverDefault?

2022-10-24 19:50 UTC, zzmp commented on src/components/SearchModal/styleds.tsx
> +    background-color: ${({ theme, disabled }) => theme.hoverDefault || (!disabled && theme.deprecated_bg2)};
Will this ever be triggered?

2022-10-24 19:50 UTC, zzmp commented on src/components/Toggle/index.tsx
> +  border: ${({ theme, isActive }) => (!isActive ? `1px solid ${theme.backgroundOutline}` : 'none')};
make this positive: `isActive ? 'none' : ...`. This is easier to read, and consistent with the line above.

2022-10-24 19:50 UTC, zzmp commented on src/pages/AppBody.tsx
> +  font-feature-settings: 'ss01' on, 'ss02' on, 'cv01' on, 'cv03' on ' : ' 'ss01' on, 'ss02' on, 'cv01' on, 'cv03' on;
this looks like it has a vestigial ternary

2022-10-25 01:26 UTC, vm commented on src/components/SearchModal/styleds.tsx
> +    background-color: ${({ theme, disabled }) => theme.hoverDefault || (!disabled && theme.deprecated_bg2)};
oh yea idk why it's like this

2022-10-25 01:52 UTC, zzmp approved these changes

2022-10-25 13:08 UTC, merged