fix: incorrectly displaying empty chart
Uniswap/interface pull request #5007
Opened 2022-10-25 21:58 UTC by cartcrom

WEB-1746 - Fixed issue where front end would not render missing chart properly. Also updated missing chart component to match design

2022-10-25 22:10 UTC, zzmp requested changes
Breaks the TokenDetails skeleton - the skeleton should be updated to match up with any layout changes to TokenDetails or its subcomponent.s

2022-10-25 22:13 UTC, zzmp requested changes

2022-10-25 22:13 UTC, zzmp commented on src/components/Tokens/TokenDetails/ChartSection.tsx
> +  margin-bottom: ${({ gap }) => gap && '24px'};
The vertical size of the Chart should be consistent, or the skeleton loader will not match what is actually loaded (this may be feedback for design).

2022-10-28 19:24 UTC, closed without merging

2022-10-28 19:24 UTC, cartcrom commented
Closing in favor of #5030