fix: update analytics package to use default event
Uniswap/interface pull request #5213
Opened 2022-11-14 23:48 UTC by dannydaniil

Your PR title must follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary), and should start with one of the following [types](https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#type):

- build: Changes that affect the build system or external dependencies (example scopes: yarn, eslint, typescript)
- ci: Changes to our CI configuration files and scripts (example scopes: vercel, github, cypress)
- docs: Documentation only changes
- feat: A new feature
- fix: A bug fix
- perf: A code change that improves performance
- refactor: A code change that neither fixes a bug nor adds a feature
- style: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)
- test: Adding missing tests or correcting existing tests

Example commit messages:

- feat: adds support for gnosis safe wallet
- fix: removes a polling memory leak
- chore: bumps redux version

Other things to note:

- Please describe the change using verb statements (ex: Removes X from Y)
- PRs with multiple changes should use a list of verb statements
- Add any relevant unit / integration tests
- Changes will be previewable via vercel. Non-obvious changes should include instructions for how to reproduce them

2022-11-14 23:49 UTC, adjkant approved these changes

2022-11-14 23:50 UTC, zzmp requested changes
Please either clear out the PR description or (preferably) update it to describe the PR

2022-11-14 23:51 UTC, zzmp commented on package.json
> +}
keep the newline at the end (otherwise its unnecessary file churn)

2022-11-15 16:29 UTC, zzmp approved these changes

2022-11-15 16:37 UTC, merged