feat: consolidating fee columns
Uniswap/interface pull request #5713
Opened 2022-12-16 17:11 UTC by aballerr

https://uniswaplabs.atlassian.net/browse/WEB-1887
https://uniswaplabs.atlassian.net/browse/WEB-1888

2022-12-22 17:04 UTC, cbachmeier requested changes
Found some minor bugs. But aligned with our tech debt strategy there are a lot of components here that should be converted to Styled components and static strings that should be internationalized

2022-12-22 17:07 UTC, cbachmeier commented on src/nft/components/profile/list/NFTListingsGrid.tsx
> +        {asset.lastPrice ? `${asset.lastPrice.toFixed(2)} ETH` : '-'}
For most places we go to 3 decimals, can you check with design that 2 is intentional here. For example on Ikegai the floor we show on the collection page is 0.001 but on his list page it shows as 0.00. We also have some auto formatting functions in currency utils that handle trailing zeroes.
![Screen Shot 2022-12-22 at 08 56 38 ](https://user-images.githubusercontent.com/11512321/209188675-43248778-6665-40a9-9262-18c02dd057ff.png)

2022-12-22 18:26 UTC, aballerr commented on src/nft/components/profile/list/NFTListingsGrid.tsx
> +              <Box as="img" width="32" src="/nft/svgs/minusCircle.svg" alt="Remove item" />
This is an existing issue on prod when multiple markets are selected, but I will try and fix

2023-01-03 22:15 UTC, cbachmeier approved these changes
LGTM. Going to move updating styled components to the follow-up PR to prevent scope creep and get other eyes on the PR

2023-01-04 17:49 UTC, merged