fix: refetch and caching policy for search bar (prices r too stale)
Uniswap/interface pull request #5759
Opened 2022-12-21 22:27 UTC by lynnshaoyu

https://uniswaplabs.atlassian.net/browse/WEB-2494?atlOrigin=eyJpIjoiMTE2N2Q0ZDcyMzZkNDk2NWFhMTRkOGM2NjkzM2NlN2UiLCJwIjoiaiJ9

2022-12-21 22:28 UTC, lynnshaoyu commented on src/nft/components/explore/Banner.tsx
> -      refetchOnReconnect: false,
btw I'm not sure if I should be doing this, but I just noticed nft collection page and banner was also not refetching prices - was that deliberate or nah?

2022-12-21 23:09 UTC, cbachmeier reviewed
Discussed on slack, this does not fix the issue with search history data being stale but removing refetchOnMount flag for fetchTrendingTokens would improve data accuracy for that query

2022-12-22 02:32 UTC, zzmp requested changes
By refetching any entry in searchHistory, you essentially deprecate all but the address field of searchHistory. Could you either simplify it, so it only stores the address and type; or expand it, so that the refetch logic is contained within useSearchHistory?

2022-12-22 02:32 UTC, zzmp commented on src/components/NavBar/SearchBarDropdown.tsx
> +          ? fetchSearchCollections(tokenOrCollection.address)
These are not actually searches, as you know the specific address. You should ask the BE if there is a more appropriate endpoint, or if it is correct usage to re-use the existing endpoints with a fully specified address.

2022-12-22 02:32 UTC, zzmp commented on src/components/NavBar/SearchBarDropdown.tsx
> +      queryKey: ['tokenOrCollectionAddress', tokenOrCollection.address],
this could really just be `['address', tokenOrCollection.address]`

2022-12-22 16:40 UTC, cbachmeier commented on src/components/NavBar/SearchBarDropdown.tsx
> +        refetchOnMount: false,
Do we want to set this flag to false?

2022-12-22 16:40 UTC, cbachmeier commented on src/components/NavBar/SearchBarDropdown.tsx
> +  historyLatestPricesQueries.flatMap((elem) => (elem.data !== undefined ? [elem.data[0]] : [])) : []
if the call fails do we want to fallback to the past price?

2023-01-12 23:32 UTC, lynnshaoyu commented
carter's gql migration makes this unnecessary

2023-01-12 23:32 UTC, closed without merging