Update unsupported.tokenlist.json
Uniswap/interface pull request #5766
Opened 2022-12-22 22:30 UTC by ianlapham

Add new token to unsupported list.

2022-12-22 22:32 UTC, zzmp requested changes

2022-12-22 22:32 UTC, zzmp commented on src/constants/tokenLists/unsupported.tokenlist.json
> +    },  `
There's a stray character in this line.

2022-12-22 23:24 UTC, ianlapham commented on src/constants/tokenLists/unsupported.tokenlist.json
> +    },  `
Thats what i get for coding on a plane

2022-12-22 23:25 UTC, ianlapham commented on src/constants/tokenLists/unsupported.tokenlist.json
> +    },  `
updating

2022-12-23 00:22 UTC, zzmp approved these changes

2023-04-05 20:56 UTC, tinaszheng approved these changes

2023-05-01 15:29 UTC, closed without merging