chore: bump dep versions
Uniswap/interface pull request #6128
Opened 2023-03-10 21:56 UTC by JFrankfurt

2023-03-10 22:30 UTC, zhongeric approved these changes
nice, just curious why we need to bump sdk core?

2023-03-10 23:23 UTC, zzmp requested changes
please include in PR description _why_ we need to bump these version

2023-03-10 23:23 UTC, zzmp commented on yarn.lock
> +  version "3.2.2"
looks like this snuck in there - it shouldn't be touched based on the package.json changes

2023-03-10 23:31 UTC, JFrankfurt commented
@zzmp

Eric Zhong
  [2 hours ago](https://uniswapteam.slack.com/archives/C04QET5UFEJ/p1678485052049259)
We just released smart order router 3.6.1 to support the new bsc deployment addresses! 
[@Jordan Frankfurt](https://uniswapteam.slack.com/team/U01KN7JV9U7)
 feel free to bump in interface to support client side routing

2023-03-11 00:10 UTC, zzmp approved these changes

2023-03-11 01:20 UTC, merged