fix: link to lowercase chain name from position page
Uniswap/interface pull request #6195
Opened 2023-03-20 16:51 UTC by vm

Previously, the backend chain name was used for linking purposes. However, this is not ideal because those values are uppercased. Similarly, they won't support any chains that aren't supported by the backend (ex: Optimism Goerli).

Instead, we create a separate mapping of SupportedChainId -> url name. I'm pretty sure most of this file should move to using SupportedChainId as the primary key, but can move to that incrementally.

Test:
- Go to a position page on a chain which the graphql API supports (ex: mainnet) and click on a token (should take to token details with a lowercase chain in url.
- Go to a position page on a chain which the graphql API does not support (ex: goerli) and click on a token (should take to etherscan).

2023-03-20 16:52 UTC, vm commented on src/graphql/data/util.tsx
> +export const CHAIN_ID_TO_URL_NAME: Record<SupportedChainId, string> = {
this maybe should live in a different file also. it is starting to not deal with graphql specific things

2023-03-20 17:54 UTC, vm commented on src/graphql/data/util.tsx
> +export const CHAIN_ID_TO_URL_NAME: Record<SupportedChainId, string> = {
i will deal with moving this later once i migrate the token details page to also use this constant. lmk if you have a better idea for the naming!

2023-03-22 03:57 UTC, lynnshaoyu approved these changes

2023-03-22 03:59 UTC, lynnshaoyu commented on src/graphql/data/util.tsx
could be helpful to add inline developer documentation here about how this is distinct from CHAIN_ID_TO_BACKEND_NAME (ie: has mappings for all chains that FE supports, which is a superset of BE chains)

2023-03-22 03:59 UTC, lynnshaoyu approved these changes
approved with suggestion for documentation

2023-03-23 12:08 UTC, grabbou requested changes
Overall, the PR looks good, but I am requesting changes to clarify whether we need a separate mapping vs reuse existing one.

2023-03-23 12:08 UTC, grabbou commented on src/graphql/data/util.tsx
> +  [SupportedChainId.OPTIMISM_GOERLI]: 'optimism_goerli',
This is what it looks like right now:
```js
export const CHAIN_IDS_TO_NAMES = {
  [SupportedChainId.MAINNET]: 'mainnet',
  [SupportedChainId.GOERLI]: 'goerli',
  [SupportedChainId.POLYGON]: 'polygon',
  [SupportedChainId.POLYGON_MUMBAI]: 'polygon_mumbai',
  [SupportedChainId.CELO]: 'celo',
  [SupportedChainId.CELO_ALFAJORES]: 'celo_alfajores',
  [SupportedChainId.ARBITRUM_ONE]: 'arbitrum',
  [SupportedChainId.ARBITRUM_GOERLI]: 'arbitrum_goerli',
  [SupportedChainId.OPTIMISM]: 'optimism',
  [SupportedChainId.OPTIMISM_GOERLI]: 'optimism_goerli',
  [SupportedChainId.BNB]: 'bnb',
}
```

2023-03-23 12:25 UTC, vm commented on src/graphql/data/util.tsx
> +  [SupportedChainId.OPTIMISM_GOERLI]: 'optimism_goerli',
great point, i did not notice we had this constant! i'll update the PR.

2023-03-27 15:57 UTC, grabbou approved these changes
LGTM

2023-03-27 18:41 UTC, merged