fix: redo MP drawer layout changes with mobile fixed
Uniswap/interface pull request #6280
Opened 2023-03-30 23:19 UTC by just-toby

## Description

this is the same change as #6260  but with the mobile behavior fixed, and an extra e2e test added. the original PR was completely missing the mobile changes we need.

[context here](https://uniswapteam.slack.com/archives/C02T729PMQE/p1680214677184219)

## Screen Capture
| Before           | After           |
| ---------------- |-----------------|
|  

https://user-images.githubusercontent.com/66155195/228985257-fbc55321-4312-4c37-8838-5c08a40770ed.MP4 

| 

https://user-images.githubusercontent.com/66155195/228985605-07a0d12c-8816-4aea-bbb6-f6afc797165b.mov 

|

## Test Plan
#### Manual
manually verified the mobile behavior this time, in addition to the regular desktop behavior.

added an e2e test to verify that you can close the bottom sheet by tapping on the scrim on mobile

#### Automated
- [ ] Unit test
- [x] Integration/E2E test

2023-04-04 18:12 UTC, cartcrom requested changes
I'm not able to click anything under DRAWER_MARGIN it seems while on mobile

https://user-images.githubusercontent.com/39385577/229880815-bf807887-c021-4aba-ad4f-227adeb86522.mov

2023-04-04 18:12 UTC, cartcrom commented on src/components/WalletDropdown/index.tsx
> +    </Wrapper>
w/ adding a new level of wrapping, I think we could improve our naming convention here, potentially:
```
<Container>
    <Wrapper>
        <ScrollBoundary ref={scrollRef}>
        </ScrollBoundary>
   </Wrapper>
</Container>
```

2023-04-04 23:48 UTC, just-toby commented
@cartcrom thanks for the check - i've added another e2e test for mobile navigation to catch that case too

2023-04-05 16:50 UTC, cartcrom approved these changes
LGTM, thx for adding tests!

2023-04-10 17:56 UTC, zzmp requested changes

2023-04-10 17:56 UTC, zzmp commented on cypress/e2e/landing.test.ts
> +    cy.viewport(375, 667)
Where are these numbers from? Can you leave a comment, and maybe make them a constant?

```
const DESKTOP_DIMENSIONS = [2000, 1600]
const MOBILE_DIMENSIONS = [375, 667]
...
cy.viewport(...DESKTOP_DIMENSIONS)
...
cy.viewport(...MOBILE_DIMENSIONS)
```

2023-04-10 17:56 UTC, zzmp commented on cypress/e2e/wallet-dropdown.test.ts
> +    cy.viewport('iphone-6')
why not use an alias like this in landing.test.ts? Then you wouldn't need *_DIMENSIONS.

2023-04-10 17:56 UTC, zzmp commented on src/components/WalletDropdown/index.tsx
> +    margin-right: ${({ open }) => (open ? 0 : '-' + DRAWER_WIDTH_XL)};
```suggestion
    margin-right: ${({ open }) => (open ? 0 : `-${DRAWER_WIDTH_XL}`)};
```

2023-04-10 19:26 UTC, zzmp approved these changes

2023-04-10 19:53 UTC, merged