chore: removing unnecessary data in assets query
Uniswap/interface pull request #6301
Opened 2023-04-04 18:57 UTC by JackShort

Removing data for the assets query cuts initial response data size in half

2023-04-04 21:28 UTC, cartcrom approved these changes

2023-04-04 21:28 UTC, cartcrom commented on src/graphql/data/nft/NftBalance.ts
> +  disabled = false
nit: rather than `disabled` just keep the name `skip` for simplicity

2023-04-05 03:28 UTC, tinaszheng approved these changes

2023-04-06 17:04 UTC, cbachmeier requested changes

2023-04-06 17:04 UTC, cbachmeier commented on src/graphql/data/nft/Asset.ts
> -            rank
Rarity no longer appearing on cards 
![Screen Shot 2023-04-06 at 10 01 08 ](https://user-images.githubusercontent.com/11512321/230446478-cd01f02a-a447-4c39-aea8-bd248fd18df1.png)

2023-04-06 18:00 UTC, cbachmeier approved these changes
LGTM

2023-04-06 18:04 UTC, merged