fix: prevent crashes on /add and /remove on unsupported chains
Uniswap/interface pull request #6346
Opened 2023-04-12 00:52 UTC by vm

## Description

_JIRA ticket:_
_Slack thread:_
_Relevant docs:_

## Screen capture

| Before       | After (Desktop) | After (Mobile) |
| ------------ |---------------- | -------------- |
| paste_before | past_after      | paste_after    |

## Test plan

### Reproducing the error

1. 

### QA (ie manual testing)

- [ ] N/A

#### Devices

### Automated testing

- [ ] Unit test
- [ ] Integration/E2E test

2023-04-19 22:00 UTC, zzmp requested changes

2023-04-19 22:00 UTC, zzmp commented on src/pages/RemoveLiquidity/V3.tsx
>    return <Remove tokenId={parsedTokenId} />
Don't negate:

```suggestion
  if (isSupportedChain(chainId)) {
    return <Remove tokenId={parsedTokenId} />
  } else {
    return <PositionPageUnsupportedContent />
  }
```

2023-04-20 17:18 UTC, grabbou approved these changes
LGTM

2023-04-20 18:40 UTC, zzmp approved these changes

2023-04-20 18:54 UTC, merged