build: send url without hash to sentry
Uniswap/interface pull request #6352
Opened 2023-04-12 19:23 UTC by vm

## Description
Re-writes the URL sent to Sentry logs to not have a hash in it. We use HashRouter from react-router to support IPFS, but this leads to issues in Sentry where the hash is picked up as a fragment (see https://romain-clement.net/articles/sentry-url-fragments/#url-fragments).

Instead, we use the method shown in that post to remove the hash in the url.
app.uniswap.org -> app.uniswap.org
app.uniswap.org/# -> app.uniswap.org
app.uniswap.org/#/pools -> app.uniswap.org/pools

_Slack thread:_ https://uniswapteam.slack.com/archives/C050USFTS5B/p1681312677826209

### QA (ie manual testing)
![image](https://user-images.githubusercontent.com/4899429/231563094-ae7cea10-6291-4bb3-bab8-bb51130d8c33.png)
![image](https://user-images.githubusercontent.com/4899429/231563110-86960bf3-4ef0-4d31-894d-751194483509.png)

### Automated testing
- [x] Unit test (N/A)
- [x] Integration/E2E test (N/A)

2023-04-12 19:25 UTC, zzmp commented on src/tracing/index.ts
> +  if (event.request?.url) {
Add a comment above the conditional explaining what you're doing (possibly linking to the referenced blog post?).

2023-04-12 19:26 UTC, zzmp commented on src/tracing/index.ts
> +const beforeSend: Required<ClientOptions>['beforeSend'] = (event: ErrorEvent, hint: EventHint) => {
I think you should just inline this, considering it is in the same file as its usage.

2023-04-12 20:30 UTC, lynnshaoyu approved these changes

2023-04-12 22:44 UTC, zzmp requested changes

2023-04-12 22:44 UTC, zzmp commented on src/tracing/index.ts
> +     * More context here: https://romain-clement.net/articles/sentry-url-fragments/#url-fragments
```suggestion
     * See https://romain-clement.net/articles/sentry-url-fragments/#url-fragments
```

2023-04-12 22:44 UTC, zzmp commented on src/tracing/index.ts
> +    /**
This is a comment, not a doc-comment, so use `/*` not `/**`:

```suggestion
    /*
```

2023-04-12 22:44 UTC, zzmp commented on src/tracing/index.ts
> +      event.request.url = event.request.url.replace('/#', '')
This should include a test in `src/tracing/index.test.ts`.

2023-04-13 21:49 UTC, zzmp approved these changes

2023-04-13 21:49 UTC, merged