test: swap modal footer unit test
Uniswap/interface pull request #6353
Opened 2023-04-12 19:44 UTC by lynnshaoyu

unit test for SwapModalFooter.tsx

2023-04-13 17:39 UTC, JFrankfurt approved these changes

2023-04-13 17:39 UTC, JFrankfurt commented on src/components/swap/SwapModalFooter.test.tsx
> +        disabledConfirm={true}
nit:
```suggestion
        disabledConfirm
```

2023-04-13 21:01 UTC, lynnshaoyu commented on src/components/swap/SwapModalFooter.test.tsx
> +        disabledConfirm={true}
done ty

2023-04-24 21:41 UTC, zzmp requested changes

2023-04-24 21:41 UTC, zzmp commented on src/components/swap/SwapModalFooter.test.tsx
> +  it('matches base snapshot', () => {
```suggestion
  it('renders with a disabled button with no account', () => {
```

2023-04-27 19:06 UTC, zzmp approved these changes

2023-04-27 19:07 UTC, merged