fix: deduplicate remote and local tx lists
Uniswap/interface pull request #6438
Opened 2023-04-24 20:29 UTC by JFrankfurt

## Description
this uses the nonce field on a transaction to remove outdated transactions from the pending tx set

_JIRA ticket:_ https://uniswaplabs.atlassian.net/browse/WEB-3168

## Test plan
submit a transaction on goerli with a very low gas price, then immediately "speed it up" or "cancel" the transaction from your wallet. Observe that once the second transaction is confirmed you'll see the pending tx from the interface removed.

### Reproducing the error
1. send a swap with a very low fee
2. send a replacement/cancellation transaction
3. observe the pending transaction (1) hanging around forever

### Automated testing
- [x] Integration/E2E test

2023-05-08 13:44 UTC, cmcewen requested changes
looks like you have some type errors to fix here. also - i like adding the nonce to the transactions, but i'm wondering if there is a different want to do this other than the hook. even though you useEffect it, i don't love a hook that mutates getting called in the render lifecycle. is there any other way to do this? like look in the reducer when you get confirmation of the replacement tx? keep the localtx but dedupe it in the view to only show a confirmed one with that nonce?

2023-05-08 21:53 UTC, zzmp commented
> is there any other way to do this? like look in the reducer when you get confirmation of the replacement tx? keep the localtx but dedupe it in the view to only show a confirmed one with that nonce?

I think this should be handled in the reducer. Your duplicate tx is new state, and once you add it via dispatch, the reducer should take care of de-duping it, so it doesn't need to run in a hook / in the render cycle.

Whether or not you also show the canceled tx is something that I'd defer to the design team for.

2023-05-09 15:28 UTC, JFrankfurt commented
> I think this should be handled in the reducer. Your duplicate tx is new state, and once you add it via dispatch, the reducer should take care of de-duping it, so it doesn't need to run in a hook / in the render cycle.

The remote transactions don't ever enter the reducer--they're maintained in component state. Only transactions generated by the application get stored in the reducer, so we can't use the `addTransaction` handler on the reducer to dedupe by nonce, since it never gets run w/ the replacement tx.

2023-05-09 17:40 UTC, JFrankfurt commented on src/lib/hooks/transactions/updater.tsx
> +  pendingTransactions: { [hash: string]: TransactionDetails }
this was incorrectly typed

2023-05-09 20:20 UTC, cmcewen approved these changes

2023-05-09 20:20 UTC, cmcewen commented on src/lib/hooks/transactions/updater.tsx
> +                provider.getTransactionCount(account).then((transactionCount) => {
nit but i prefer async/await 😄

2023-05-09 20:20 UTC, cmcewen commented on src/state/transactions/reducer.test.ts
> +      expect(store.getState()[SupportedChainId.MAINNET]['abc']).toBeUndefined()
💯

2023-05-09 20:20 UTC, cmcewen commented on src/state/transactions/reducer.ts
> +interface AddTransactionPayload {
❤️

2023-05-09 20:20 UTC, cmcewen commented on src/state/transactions/updater.tsx
> +  }, [chainId, transactions])
can you verify that nothing else relied on this incorrect behavior?

2023-05-09 20:20 UTC, cmcewen commented on src/lib/hooks/transactions/updater.tsx
> +                  if (tx.nonce && tx.nonce < transactionCount) {
can you add a comment to make it clear to keep the tx.nonce check because old saved txs won't have a tx.nonce?

2023-05-10 16:00 UTC, JFrankfurt commented on src/state/transactions/updater.tsx
> +  }, [chainId, transactions])
confirmed--a more involved modification was happening subsequently on line 18 of `src\lib\hooks\transactions\updater.tsx` before the incorrect data was used

2023-05-10 16:59 UTC, cmcewen approved these changes

2023-05-11 16:44 UTC, JFrankfurt commented on src/components/AccountDrawer/MiniPortfolio/Activity/index.tsx
> +      Object.keys(remoteMap).some((remoteHash) => remoteMap[remoteHash]?.nonce === localActivity.nonce)
I added this so that the local nonce never renders. Before the duplicate was rendering until the next block triggered a refresh.

2023-05-11 17:35 UTC, just-toby approved these changes

2023-05-11 17:35 UTC, just-toby commented on cypress/e2e/mini-portfolio/activity-history.test.ts
> +          {
suggestion: move this to a separate file so this test is easier to read

2023-05-11 17:35 UTC, just-toby commented on src/lib/hooks/transactions/updater.tsx
> +                  removeTransaction(hash)
if this happens, do we still want to throw the `RetryableError` below?

2023-05-11 18:16 UTC, merged