build: set version on sentry release
Uniswap/interface pull request #6440
Opened 2023-04-24 22:06 UTC by vm

## Description
Right now we have cases where this error shows up.
<img width="906" alt="Screen Shot 2023-04-24 at 6 05 45 PM" src="https://user-images.githubusercontent.com/4899429/234126837-4178b1e6-222d-4331-a428-31c7d5fd4121.png">

I believe it's because we're not adding the release version into the github action which actually uploads the sourcemaps.
https://github.com/getsentry/action-release#parameters

## Test plan
I believe we have to merge this to see what happens on deploy tomorrow honestly.

2023-04-24 22:35 UTC, cmcewen requested changes
is there a way to make sure these things are updated at the same time? for example if we were to start using a different way to version releases, how could we ensure this wouldn't break?

2023-04-24 22:53 UTC, vm commented
We'd need a way to save a `SENTRY_RELEASE` variable somewhere, then read it in the Github action. Doable though...

2023-04-24 23:53 UTC, zzmp requested changes

2023-04-24 23:53 UTC, zzmp commented on .github/workflows/release.yaml
> +          version: ${{ github.sha }}
Isn't this the default? Why would this have not worked before?

2023-04-25 15:24 UTC, vm commented
Turns out this is the default as zach said.

2023-04-25 15:24 UTC, closed without merging