fix: match OneKey more generically
Uniswap/interface pull request #6461
Opened 2023-04-27 20:12 UTC by vm

## Description
Extends the match to handle this error: https://uniswap-labs.sentry.io/issues/4009216608/?project=4504255148851200&referrer=release-issue-stream

It says just OneKey instead of OneKey.app.

## Test plan
### Automated testing
- [x] Unit test
- [x] Integration/E2E test (Na)

2023-04-27 20:27 UTC, zzmp requested changes

2023-04-27 20:27 UTC, zzmp commented on src/tracing/errors.test.ts
> +    it('filter errors with OneKey.app', () => {
```suggestion
    it('filter OneKey errors (macOS users)', () => {
```

2023-04-27 20:27 UTC, zzmp commented on src/tracing/errors.test.ts
> +    it('filter errors with just OneKey', () => {
```suggestion
    it('filter OneKey errors (Windows users)', () => {
```

2023-04-27 21:08 UTC, zzmp approved these changes

2023-05-01 15:02 UTC, vm commented
<img width="906" alt="Screen Shot 2023-05-01 at 11 02 01 AM" src="https://user-images.githubusercontent.com/4899429/235472975-99ce6963-9839-4477-b63b-e80fd95f9781.png">

still errors after sourcemap fixes, so going to merge this

2023-05-01 15:02 UTC, merged