test(e2e): (un/)wrap transactions
Uniswap/interface pull request #6474
Opened 2023-05-01 15:31 UTC by JFrankfurt

## Description
This introduces two new Cypress E2E tests for the process of wrapping and unwrapping ETH using the swap interface. These tests aim to ensure that the application's functionality for converting between ETH and WETH works as expected and to catch any possible regressions in future updates.

The following tests are added:

**Wrapping ETH:** This test checks if the user is able to wrap ETH into WETH successfully. It verifies that the pending transaction indicator is shown and disappears once the transaction is mined, the UI balance increases, a successful wrap notification is displayed, and the user's WETH account balance increases accordingly.

**Unwrapping WETH:** This test checks if the user is able to unwrap WETH back into ETH successfully. Similar to the wrapping test, it verifies the pending transaction indicator behavior, UI balance update, successful unwrap notification, and that the user's WETH account balance decreases to zero.

_JIRA ticket:_ https://uniswaplabs.atlassian.net/browse/WEB-3260

2023-05-02 06:03 UTC, zzmp requested changes

2023-05-02 06:03 UTC, zzmp commented on cypress/e2e/swap.test.ts
> +            cy.get(getTestSelector('wrap-button')).click()
Add a comment as to what you're doing

2023-05-02 06:03 UTC, zzmp commented on cypress/e2e/swap.test.ts
> +          cy.get(getTestSelector('wrap-button')).click()
Add a comment as to what you're doing.

2023-05-02 18:26 UTC, zzmp approved these changes

2023-05-03 01:45 UTC, cartcrom approved these changes
LGTM! very clean

2023-05-03 04:51 UTC, merged