fix: time interval axis overlap
Uniswap/interface pull request #6717
Opened 2023-06-06 22:03 UTC by JackShort

## Description
* fixed interval overlapped caused by `interval.every(5)` being undefined initially so it was rendering 30 intervals (1 for every other second) which caused an overlap

_Linear ticket:_ https://linear.app/uniswap/issue/WEB-1842/[web][tokens]-there-is-an-overlap-when-user-select-1h
_Slack thread:_
_Relevant docs:_

### Before
![Screen Shot 2023-06-06 at 5 46 04 PM](https://github.com/Uniswap/interface/assets/9094792/c3b0e3d6-6d52-49f3-babf-1765c790a479)

### After
![Screen Shot 2023-06-06 at 6 00 18 PM](https://github.com/Uniswap/interface/assets/9094792/bb616a24-47c3-4281-9b89-38d5f3e84172)

2023-06-07 16:52 UTC, cbachmeier requested changes
Still seeing the bug for [Polygon USDC](https://interface-git-johnshort-web-1842-webtokens-there-ccae8c-uniswap.vercel.app/#/tokens/polygon/0x2791bca1f2de4661ed88a30c99a7a9449aa84174)
![Screen Shot 2023-06-07 at 09 51 31 ](https://github.com/Uniswap/interface/assets/11512321/06c6e33f-47b4-415e-9309-951032fcb702)

2023-06-07 16:56 UTC, cbachmeier commented
Did some more testing. When I went back to the Token Explore page and then returned to the Polygon USDC page the error persisted but was cleared and did not re-appear if I refreshed the Polygon USDC page. I then switched chains to Arbitrum and was able to reproduce for Arbitrum USDC
![Screen Shot 2023-06-07 at 09 56 02 ](https://github.com/Uniswap/interface/assets/11512321/8aae2ec5-31c7-4dee-9e46-c3757efce8f8)

2023-06-07 16:57 UTC, cbachmeier commented
![Screen Shot 2023-06-07 at 09 57 12 ](https://github.com/Uniswap/interface/assets/11512321/0800bdec-40a7-45a2-a5e8-065897688dc2)
not exclusive to stables

2023-06-07 17:04 UTC, cbachmeier commented
Can no longer replicate at all, I think it might have been a caching error on my device

2023-06-07 17:13 UTC, cbachmeier reviewed
LGTM. Unable to reproduce error. Minor nit

2023-06-07 17:13 UTC, cbachmeier commented on src/components/Tokens/TokenDetails/PriceChart.tsx
> +            .range(startDateWithOffset, endDateWithOffset, interval ? 2 : 10)
nit: can you set `2` and `10` as named consts?

2023-06-07 17:15 UTC, cbachmeier commented
Check that. Can replicate with obscure tokens https://interface-git-johnshort-web-1842-webtokens-there-ccae8c-uniswap.vercel.app/#/tokens/ethereum/0x644192291cc835a93d6330b24ea5f5fedd0eef9e

2023-06-07 20:23 UTC, cbachmeier approved these changes
LGTM

2023-06-08 17:24 UTC, just-toby approved these changes

2023-06-08 17:26 UTC, merged