fix: remove gradientId from svg props
Uniswap/interface pull request #6751
Opened 2023-06-12 15:16 UTC by sarobolket

## Description
FIX: React does not recognize the `gradientId` prop on a DOM element in the NFT page like this => https://app.uniswap.org/#/nfts/asset/0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d/4402

2023-06-12 21:41 UTC, JFrankfurt approved these changes

2023-06-14 03:16 UTC, zzmp approved these changes

2023-06-14 03:18 UTC, zzmp requested changes
Could you merge `main` into this PR to fix the failing unit test? It should be fixed on `main`.

I couldn't reproduce the error that you're trying to fix. Can you tell me what I should be looking for in the link?

2023-06-14 07:27 UTC, sarobolket commented
@zzmp You can see the warning only in development mode.

2023-06-14 15:41 UTC, zzmp approved these changes

2023-06-14 16:14 UTC, merged

2023-06-14 16:14 UTC, zzmp commented
@sarobolket thanks for cleaning this up!