fix: currency select modal when chain is not supported
Uniswap/interface pull request #6759
Opened 2023-06-13 22:38 UTC by JackShort

* fixes a bug where if you select the token select modal when connected to an unsupported network it will throw and error

2023-06-13 22:42 UTC, cbachmeier requested changes

2023-06-13 22:42 UTC, cbachmeier commented on src/nft/components/bag/BagFooter.tsx
>      <FooterContainer>
I think it'd be better to hide the whole section so you don't get this view
![Screen Shot 2023-06-13 at 15 41 26 ](https://github.com/Uniswap/interface/assets/11512321/dd36823c-9715-4a5e-a757-3949aad40078)

2023-06-14 23:09 UTC, cbachmeier approved these changes

2023-06-15 16:10 UTC, just-toby commented on src/nft/components/bag/BagFooter.tsx
> +  const chainAllowed = isSupportedChain(chainId)
this variable is used once, you could just use `isSupportedChain(chainId)` on L465 instead

2023-06-15 16:10 UTC, just-toby approved these changes

2023-06-15 16:15 UTC, just-toby approved these changes

2023-06-15 16:39 UTC, merged