fix: 0 showing as collected fee amount
Uniswap/interface pull request #6804
Opened 2023-06-20 20:10 UTC by JackShort

## Description
* fixes bug where 0s are showed for the amount when collecting LP position fee

_Linear ticket:_ https://linear.app/uniswap/issue/WEB-1906/fee-collection-from-pool-appearing-as-0-in-activity-feed

## Screen capture

### Before
![Screen Shot 2023-06-20 at 4 09 55 PM](https://github.com/Uniswap/interface/assets/9094792/64995d32-b0c6-4af2-aed0-c6b993fa3b67)

### After
![Screen Shot 2023-06-20 at 4 08 25 PM](https://github.com/Uniswap/interface/assets/9094792/82f4818d-8368-432b-ad1a-812c6b65d874)

2023-06-20 20:16 UTC, zzmp requested changes
Can you construct a unit test with mocked network responses (unit tests should not rely on network)?

2023-06-20 20:26 UTC, JackShort commented
> Can you construct a unit test with mocked network responses (unit tests should not rely on network)?

we actually have this in `parseLocal` and tests and it tests all of the functions that

2023-06-30 21:29 UTC, zzmp requested changes
sorry last nit to get the tests up to prevent regressing

2023-06-30 21:29 UTC, zzmp commented on src/pages/Pool/PositionPage.test.tsx
> +    expect(screen.getByText('Collect fees')).toBeInTheDocument()
You mock it so it renders actual numbers, but you should also assert on that: expect(...).toContain(actualNumbers)...

2023-07-05 21:21 UTC, zzmp approved these changes

2023-07-07 16:40 UTC, vm approved these changes

2023-07-07 16:51 UTC, merged