fix: combine userState with default injected wallet in cypress setup
Uniswap/interface pull request #6849
Opened 2023-06-27 18:21 UTC by just-toby

## Description

this allows you to set custom `userState` in a test in combination with the default injected hardhat provider being automatically connected. 

## Test plan

### Reproducing the error

1.  write a test with both the `hardhat` option and some custom initial `userState` and note that the wallet isn't automatically connected at the start of the test

### QA (ie manual testing)

- [x] verified the wallet connects automatically with this change

2023-06-30 21:14 UTC, zzmp requested changes
Two tests rely on a disconnected state. I'm not sure why they are still passing with your changes:

https://github.com/Uniswap/interface/blob/main/cypress/e2e/landing.test.ts#L6
https://github.com/Uniswap/interface/blob/main/cypress/e2e/wallet-connection/connect.test.ts#L30

2023-07-05 21:24 UTC, zzmp approved these changes

2023-07-06 19:23 UTC, vm approved these changes

2023-07-06 19:23 UTC, vm commented on cypress/support/commands.ts
> +                options?.userState
could do `{ ...CONNECTED_WALLET_USER_STATE, ...(options?.userState ?? {}) }`

2023-07-06 19:23 UTC, vm commented on cypress/utils/user-state.ts
> +export const UNCONNECTED_WALLET_USER_STATE: Partial<UserState> = { selectedWallet: undefined }
DISCONNECTED?

2023-07-06 20:12 UTC, vm approved these changes

2023-07-06 21:01 UTC, merged