fix margins for nav
Uniswap/interface pull request #6908
Opened 2023-07-10 18:49 UTC by LunrEclipse

## Description

Added conditional margins to `MenuItem` on mobile for improved spacing. 

_Linear ticket:_ WEB-1908

## Screen capture

### Before

https://github.com/Uniswap/interface/assets/35351983/3e4d637e-8ebd-4b94-99b1-ed4a0077fc38

### After

https://github.com/Uniswap/interface/assets/35351983/cd812bd8-9e72-47f4-88bf-cf6ed5b8b12a

### QA (ie manual testing)

- [x] Test Navbar on mobile and web

### Automated testing

- [x] Unit test N/A

2023-07-10 22:02 UTC, natew approved these changes

2023-07-27 18:12 UTC, JFrankfurt requested changes
This fully pushes the `...` menu toggle off my screen.

![image](https://github.com/Uniswap/interface/assets/5773490/26ddf7be-9f04-4168-9ef2-97537ae38923)

2023-07-27 18:37 UTC, LunrEclipse commented
> This fully pushes the `...` menu toggle off my screen.
> 
> ![image](https://user-images.githubusercontent.com/5773490/256627428-26ddf7be-9f04-4168-9ef2-97537ae38923.png)

revenge of the minis 😔

2023-08-14 19:27 UTC, JFrankfurt approved these changes
lgtm

2023-08-14 19:27 UTC, merged