feat: vertical LP
Uniswap/interface pull request #7000
Opened 2023-07-24 21:59 UTC by JFrankfurt

## Description

This converts the default LP experience to be vertical instead of horizontal. 

_Linear ticket:_
_Slack thread:_
_Relevant docs:_

## Screen capture
<img width="682" alt="image" src="https://github.com/Uniswap/interface/assets/5773490/c42d3f55-9d9a-479e-89d5-20815f12a8dc">

### Before
|    Mobile    |   Desktop    |
| ------------ | ------------ |
| <img width="406" alt="image" src="https://github.com/Uniswap/interface/assets/5773490/14eda283-363b-4d4a-b5c1-1273f8ddde2f"> | <img width="907" alt="image" src="https://github.com/Uniswap/interface/assets/5773490/b9593b67-b3a1-4447-8903-bc3d7b4ca2a7"> |

### After
|    Mobile    |   Desktop   |
| ------------ | ----------- |
| <img width="394" alt="image" src="https://github.com/Uniswap/interface/assets/5773490/87c30a9e-c7aa-459d-9ea1-f611ad576187">  | <img width="682" alt="image" src="https://github.com/Uniswap/interface/assets/5773490/8121e5aa-7d66-4e41-8cb3-8cc74ed18283"> |

## Test plan

### Reproducing the error

1. 

### QA (ie manual testing)

- [ ] N/A

#### Devices

### Automated testing

- [ ] Unit test
- [ ] Integration/E2E test

2023-07-24 22:14 UTC, JFrankfurt commented on src/components/LiquidityChartRangeInput/index.tsx
> +  max-height: 150px;
@callil confirming 150 (not 148 or 152)

2023-07-31 21:39 UTC, gnewfield commented
I'm seeing a bug on pool creation at new fee tiers, where the range selector is not being shown. The range selector should be shown below the new price input. Attaching before and after screenshots for comparison. This is probably just due to the reordering, which is causing a mismatch between the components and the state variables that are used for conditional rendering.

|    Before    |   After    |
| ------------ | ------------ |
|<img width="1512" alt="Screenshot 2023-07-31 at 5 32 10 PM" src="https://github.com/Uniswap/interface/assets/18626088/490930bc-5027-4952-980a-fbdcc7d797c3"> |<img width="1512" alt="Screenshot 2023-07-31 at 5 34 54 PM" src="https://github.com/Uniswap/interface/assets/18626088/5bf78e53-b333-4071-9c77-487ac9e854e0"> |

2023-08-01 00:04 UTC, just-toby requested changes

2023-08-01 00:04 UTC, just-toby commented on src/components/CurrencyInputPanel/index.tsx
> +      {!locked && (
can we do an early return `if (locked) return null` and un-indent this JSX for readability?

2023-08-01 00:04 UTC, just-toby commented on src/components/CurrencyInputPanel/index.tsx
> +      {!locked && (
also, are we intentionally removing the `locked` UI that was shown before? see deleted Line 234.

2023-08-01 00:04 UTC, just-toby commented on src/pages/AddLiquidity/index.tsx
> +        <BodyWrapper style={{ padding: hasExistingPosition ? '10px' : 0, maxWidth: '640px' }}>
no inline style, pass a prop to the styled component

2023-08-01 19:07 UTC, cartcrom approved these changes
We should def look into Gray's bug comment, but assuming eddie's comments are fixed LGTM

2023-08-02 23:04 UTC, just-toby approved these changes

2023-08-03 00:24 UTC, just-toby approved these changes

2023-08-03 15:51 UTC, cartcrom approved these changes

2023-08-07 19:20 UTC, gnewfield approved these changes

2023-08-07 19:22 UTC, merged