chore: align @reduxjs/toolkit dep versions with wallet
Uniswap/interface pull request #7038
Opened 2023-07-27 21:43 UTC by natew

dep align

2023-08-01 18:18 UTC, cbachmeier requested changes
Can you rebase? It seems like there is a lot of unrelated changes in this PR

2023-08-02 00:47 UTC, natew commented
this is some stupid github bug i've seen happen now a few times, locally it shows the right diff

2023-08-02 00:48 UTC, natew commented
oh maybe it wasnt that bug? but i have confirmed theres a github bug where branches show a bunch of changes? but now i've merged the latest and it fixed which usually with that bug it gets stuck until you push to a new branch and here it didnt, so should be good

2023-08-02 16:46 UTC, cbachmeier approved these changes

2023-08-07 06:24 UTC, zzmp approved these changes

2023-08-07 16:47 UTC, merged