fix: use submitted icon on mainnet
Uniswap/interface pull request #7055
Opened 2023-07-31 23:43 UTC by just-toby

## Description

there are two UX changes in this PR (i'll leave comments on the code changes that implement them)
- on mainnet, show a different icon when waiting for transaction confirmation. instead of showing a green check, we show a blue arrow ie the `SubmittedIcon`
- on all chains, remove the `TradeSummary` UI in the "tx confirmed" state. and show the explorer link in its place

there's also a small refactor of the `getContent` function into the `useStepContents` hook - i found a bug in which these contents weren't updating in all expected cases because of the inner rendering function of the `steps` array. so this change is to make all the steps' contents precomputed and memoized.

_Linear ticket:_ https://linear.app/uniswap/issue/WEB-2574/swap-submit-modal-should-have-an-arrow-icon-instead-of-checkmark
_Relevant docs:_ https://www.figma.com/file/ksWAw6EZiiMuRyMQQHicoH/Permit2-Revisions?node-id=1035%3A9685&mode=dev

## Screen capture

### Before
|    Mobile    |   Desktop    |
| ------------ | ------------ |
| paste_before | paste_before |

### After
|    Mobile    |   Desktop   |
| ------------ | ----------- |
| paste_after  | paste_after |

## Test plan

### Reproducing the error

1. 

### QA (ie manual testing)

- [ ] N/A

#### Devices

### Automated testing

- [ ] Unit test
- [ ] Integration/E2E test

2023-07-31 23:43 UTC, just-toby commented on src/components/swap/PendingModalContent/index.tsx
> +        {currentStep === ConfirmModalState.PENDING_CONFIRMATION && showSubmitted && <AnimatedEntranceSubmittedIcon />}
this is the new icon for the mainnet pending state

2023-07-31 23:44 UTC, just-toby commented on src/components/swap/PendingModalContent/index.tsx
> +      }
these lines implement the change to remove the `TradeSummary` and replace it with the explorer link. all other changes in this file are just moving code around to make this function a hook

2023-08-02 17:54 UTC, cbachmeier requested changes

2023-08-02 17:54 UTC, cbachmeier commented on src/components/swap/PendingModalContent/Logos.tsx
>    width: 48px;
can you pull out these duplicate `css` styles to be shared?

2023-08-02 17:54 UTC, cbachmeier commented on src/components/swap/PendingModalContent/index.tsx
> +          revocationPending || tokenApprovalPending || wrapPending || (swapPending && !showSuccess && !showSubmitted)
we use the `revocationPending || tokenApprovalPending || wrapPending` condition a couple times, can we pull this out to its own const

2023-08-02 17:54 UTC, cbachmeier commented on src/components/swap/PendingModalContent/index.tsx
> +  const pendingConfirmationContent = useMemo(() => {
could you move this block to its own function such as `getPendingConfirmationContent` to help maintain the readability of the hook

2023-08-02 17:54 UTC, cbachmeier commented on src/components/swap/PendingModalContent/index.tsx
> +      const showSubmittedState = swapPending && chainId === ChainId.MAINNET
why do we only want to do the submitted state on Mainnet? Speed of L2s? What about other alt L1s?

2023-08-02 17:54 UTC, cbachmeier commented on src/components/swap/PendingModalContent/index.tsx
> +          bottomLabel: showSubmittedState ? t`Transaction pending...` : explorerLink,
we already know `swapPending` is true here so we could just check if current chain is Mainnet

2023-08-02 17:54 UTC, cbachmeier commented on src/components/swap/PendingModalContent/index.tsx
> +    } else if ((swapPending || swapConfirmed) && chainId && swapResult && swapResult.type === TradeFillType.Classic) {
`swapResult && swapResult.type === TradeFillType.Classic` -> `swapResult?.type === TradeFillType.Classic`

2023-08-02 17:54 UTC, cbachmeier commented on src/components/swap/PendingModalContent/index.tsx
> +  const showSuccess = swapConfirmed
this `showSuccess` const can just be replaced with `swapConfirmed`

2023-08-03 17:29 UTC, cbachmeier approved these changes

2023-08-03 19:04 UTC, JackShort approved these changes

2023-08-03 19:15 UTC, merged