fix: displays price when not updated on TDP
Uniswap/interface pull request #7068
Opened 2023-08-02 19:29 UTC by LunrEclipse

## Description

Displays that price as opposed to `Price unavailable` with a tooltip informing users that the price is not updated in the event where there is some price data, but it may not be update to date. 

_Linear ticket:_ WEB-2558

## Screen capture

### Before

<img width="387" alt="Screenshot 2023-08-02 at 3 26 01 PM" src="https://github.com/Uniswap/interface/assets/35351983/78aa7eab-cc0c-472d-ab5d-2f2575d97eb2">

<img width="1360" alt="Screenshot 2023-08-02 at 3 25 04 PM" src="https://github.com/Uniswap/interface/assets/35351983/518e34d9-b891-4f24-9831-84ec7bef1beb">

### After

<img width="392" alt="Screenshot 2023-08-02 at 3 26 26 PM" src="https://github.com/Uniswap/interface/assets/35351983/c6f449bf-8b15-4588-8d25-ad23c84208e0">

<img width="1428" alt="Screenshot 2023-08-02 at 3 24 19 PM" src="https://github.com/Uniswap/interface/assets/35351983/1d485412-6989-4d13-9d0d-c39b84f42d4f">
<img width="1423" alt="Screenshot 2023-08-02 at 3 24 40 PM" src="https://github.com/Uniswap/interface/assets/35351983/6f7ce4f6-7c72-4b93-9cc5-bd8a6d0d4d9f">

### Automated testing

- [x] Unit test N/A

2023-08-02 19:31 UTC, tinaszheng approved these changes
Nice!

2023-08-17 15:23 UTC, JFrankfurt commented on src/components/Tokens/TokenDetails/PriceChart.tsx
> +      <Trans>Price may not be up-to-date due to recently low trading volume</Trans>
This reads quite awkwardly imo.

```suggestion
      <Trans>This price may not be up-to-date due to low trading volume.</Trans>
```

2023-08-17 15:51 UTC, JFrankfurt requested changes
Add a unit test and this'll be good to go.

2023-08-17 18:27 UTC, JFrankfurt approved these changes
noice

2023-08-17 18:27 UTC, merged