fix: make sure MenuItem in navbar doesnt wrap text and overflow is cutoff if super long
Uniswap/interface pull request #7069
Opened 2023-08-02 20:06 UTC by natew

## Description

Fix wrapping in navbar

_Linear ticket:_ https://linear.app/uniswap/issue/WEB-825/[nav]-tabs-do-not-text-wrap
_Slack thread:_
_Relevant docs:_

## Screen capture

### Before

<img width="499" alt="CleanShot 2023-08-02 at 10 03 46@2x" src="https://github.com/Uniswap/interface/assets/12100/b6dc98d5-c301-4b6e-b17e-787f4bf6d32b">

### After

<img width="488" alt="CleanShot 2023-08-02 at 10 04 03@2x" src="https://github.com/Uniswap/interface/assets/12100/e1d6d3e7-83af-45f2-922b-9733d908231d">

I made it handle super super long ones, though that shouldn't ever appear, if we had some accidental translation that was like 7 words I think it's better to make it cut off than just push the entire navbar out of screen, it's pretty generous.

<img width="558" alt="CleanShot 2023-08-02 at 10 04 09@2x" src="https://github.com/Uniswap/interface/assets/12100/d93e8d6d-e7f2-461f-846c-51acdf788a8f">

## Test plan

### Reproducing the error

1. 

### QA (ie manual testing)

- [ ] N/A

#### Devices

### Automated testing

- [ ] Unit test
- [ ] Integration/E2E test

2023-08-02 22:55 UTC, just-toby approved these changes

2023-08-03 17:16 UTC, cbachmeier requested changes
This comes up frequently and needs more design input. The issue is with a breakpoints and internationalization, if we just don't wrap you get into states where menu items are cutoff. See the below screenshot where, when in Spanish, on mobile (397px), the overflow menu is now cutoff
![Screenshot 2023-08-03 at 10 14 04 AM](https://github.com/Uniswap/interface/assets/11512321/a8951be8-a612-49e4-83a3-4cdb7c9d8233)

2023-08-03 17:17 UTC, cbachmeier commented on src/components/NavBar/index.tsx
> +const MenuItemText = styled.span`
This would also be a good time refactor the `NavLink` to not use vanilla extract and to handle text wrapping

2023-08-04 20:50 UTC, natew commented
@cbachmeier ah good catch on the mobile need, perhaps that could be a scrollable horizontal input, i'll ping design

2023-09-12 17:30 UTC, natew commented
@callil i think design needs some input before this can go forward

2023-09-16 14:22 UTC, callil commented
We should use the "overflow" behavior like we do for breakpoints on the nav... so in this case the nav should be aware of how long the string lengths are and the screen width. If they will overflow, put those menu items in the triple dot overflow menu.

2023-10-04 21:36 UTC, natew commented
Closing and added to backlog to revisit https://linear.app/uniswap/issue/WEB-2945/navbar-overflowing-text-should-automatically-move-into-the-menu

2023-10-04 21:36 UTC, closed without merging