feat: bottom sheet for mobile swap settings
Uniswap/interface pull request #7072
Opened 2023-08-02 20:49 UTC by JackShort

## Description

* added a bottom sheet popup menu for swap settings on mobile

_Linear ticket:_  https://linear.app/uniswap/issue/WEB-2520/settings-dialog-content-overflow-on-small-width-w-long-translations

## Screen capture

### Before

![Screen Shot 2023-08-02 at 4 48 54 PM](https://github.com/Uniswap/interface/assets/9094792/3eb02379-6cc8-4a27-9e3c-fab9243a51bf)

### After

![Screen Shot 2023-08-02 at 4 48 54 PM](https://github.com/Uniswap/interface/assets/9094792/0d383cfa-7aaa-4abc-9f61-52ec77835f57)

2023-08-02 22:55 UTC, just-toby requested changes
add a cypress test that sets the viewport size and verifies that the correct view appears

2023-08-03 00:29 UTC, just-toby approved these changes

2023-08-09 20:21 UTC, gnewfield commented
I'm seeing a strange effect when the Slippage panel is toggled open. The Transaction deadline panel disappears for an instant (gets pushed down below the fold?), and then reappears when the panel is done opening. It's hard to notice, but I made a recording of the screen and confirmed. This is the case in prod as well, so not an issue with the bottom sheet but with the settings menu. I've made a backlog item for this in [WEB-2642](https://linear.app/uniswap/issue/WEB-2642/toggling-defect-in-the-settings-panel). Otherwise, changes look good.

2023-08-09 20:22 UTC, gnewfield approved these changes

2023-08-10 16:20 UTC, merged