fix: adjusting slippage in a different language
Uniswap/interface pull request #7073
Opened 2023-08-02 21:53 UTC by JackShort

## Description
Fixes issues where languages like French and Dutch are unable to adjust slippage because the slippage input is squished

_Linear ticket:_  https://linear.app/uniswap/issue/WEB-2522/cant-adjust-slippage-in-different-language

## Screen capture

### Before

![Screen Shot 2023-08-02 at 5 49 44 PM](https://github.com/Uniswap/interface/assets/9094792/019990d7-6ed4-4669-8ca3-922c3288c092)

### After

![Screen Shot 2023-08-02 at 5 50 46 PM](https://github.com/Uniswap/interface/assets/9094792/f2c44b79-6f25-42ab-8349-6b07e8ae9874)

2023-08-02 21:57 UTC, zzmp requested changes

2023-08-02 21:57 UTC, zzmp commented on src/components/AnimatedDropdown/index.tsx
> +  overflow = 'hidden',
Why not make all animated dropdowns use `overflow: "visible"`? couldn't this just crop up in another menu in another language?

2023-08-03 18:39 UTC, zzmp approved these changes

2023-08-03 19:05 UTC, just-toby approved these changes

2023-08-03 19:05 UTC, merged