feat: add chainId to swap_tx_completed
Uniswap/interface pull request #7094
Opened 2023-08-07 18:45 UTC by just-toby

## Description

adds a  `time_to_sign` property to the `SWAP_TRANSACTION_COMPLETED` event. which measures the elapsed time between page load and the user signing the transaction. we only report this value if that signed transaction actually completes, so we need to track `time_to_sign` timestamps by tx hash and map them to the completed transaction.

_Linear ticket:_
_Slack thread:_
_Relevant docs:_

## Screen capture

chainId addition:
<img width="599" alt="image" src="https://github.com/Uniswap/interface/assets/66155195/131fc5de-1c43-4049-a9df-adf7ed18bb77">

## Test plan

### Reproducing the error

1. 

### QA (ie manual testing)

- [ ] N/A

#### Devices

### Automated testing

- [ ] Unit test
- [ ] Integration/E2E test

2023-08-08 17:48 UTC, tinaszheng commented on src/tracing/SignedTransactionTimestampRegistry.ts
> +    return marks?.length > 0 ? marks[0].startTime : undefined
think you can just shorthand this with `marks[0]?.startTime`

2023-08-10 16:34 UTC, tinaszheng commented on src/hooks/useUniswapXSwapCallback.ts
> +          time_to_sign: performance.mark('time-to-sign-uniswapx').startTime,
why not just use the difference between Date.now() before sending the request on line 69 and after

2023-08-10 16:35 UTC, tinaszheng requested changes

2023-08-10 16:35 UTC, tinaszheng commented on src/state/transactions/updater.tsx
> +        time_to_sign: hasReportedTimeToSwap ? undefined : SignedTransactionTimestampRegistry.getInstance().get(hash),
i dot think this is right, this measures the amount of time it takes post sign -> tx is successful, whereas your time to sign should just be pre-signature -> post-signature

2023-08-14 19:22 UTC, tinaszheng approved these changes

2023-08-14 20:19 UTC, cartcrom approved these changes

2023-08-14 20:26 UTC, merged