feat: add amplitude logging for gas estimate failures
Uniswap/interface pull request #7095
Opened 2023-08-07 18:49 UTC by cbachmeier

## Description

- We've noticed an increase in swap failures so we're adding an analytics event if the `estimateGas` call fails for the data team to use for offline analysis. 
- This event adds data for swaps that fail before making it on chain. 
- Confirmed data points with @blairmason. 
- Added the new swap event to shared package [here](https://github.com/Uniswap/analytics-events/pull/49) and updated depedency

_Linear ticket:_ https://www.notion.so/uniswaplabs/Swap-fee-on-transfer-failures-aebe8b9206cf41fe9b8b8f8b26613a43
_Slack thread:_ https://uniswapteam.slack.com/archives/C05JRUHDD4L/p1691431753896049

2023-08-07 19:22 UTC, gnewfield approved these changes

2023-08-08 03:49 UTC, tinaszheng requested changes

2023-08-08 03:49 UTC, tinaszheng commented on src/hooks/useUniversalRouter.ts
> +            ...formatCommonPropertiesForTrade(trade, options.slippageTolerance),
We'll need the tx request object here to see why it failed - can you include that too?

2023-08-08 17:19 UTC, tinaszheng commented on src/hooks/useUniversalRouter.ts
> +            ...formatCommonPropertiesForTrade(trade, options.slippageTolerance),
also the `gasError` object if possible

2023-08-09 18:32 UTC, tinaszheng approved these changes

2023-08-09 19:28 UTC, merged