chore: remove e2e coverage from aggregate calculation in codecov
Uniswap/interface pull request #7108
Opened 2023-08-08 17:21 UTC by JFrankfurt

2023-08-08 18:26 UTC, zzmp approved these changes

2023-08-08 18:30 UTC, zzmp requested changes
You'll need to also remove it from `cypress/support/e2e.ts`

2023-08-08 18:51 UTC, zzmp approved these changes

2023-08-09 19:45 UTC, LunrEclipse approved these changes

2023-08-09 19:48 UTC, merged