fix: make swc not break WalletConnect by targeting a newer version of es
Uniswap/interface pull request #7139
Opened 2023-08-10 22:28 UTC by natew

fixes breaking wallet connect / uniswap wallet connect on main

to repro: it was erroring if you hit connect => uniswap wallet and not allowing connection, this should fix that

2023-08-10 22:34 UTC, zzmp requested changes

2023-08-10 22:34 UTC, zzmp commented on .swcrc
> +      "chrome": "112",
could you use the percentage format and match what we have in our package.json?
also our browserslist could probably use updating.

2023-08-10 23:22 UTC, zzmp approved these changes
Do we care about excluding op_mini?

2023-08-10 23:35 UTC, natew commented
got browser list form working but had to use 0.5 (0.25 still breaks) but that seems reasonable.

2023-08-11 01:33 UTC, zzmp approved these changes

2023-08-11 16:32 UTC, cbachmeier approved these changes

2023-08-11 17:57 UTC, merged