fix: add distance from white check for token rich link previews
Uniswap/interface pull request #7152
Opened 2023-08-14 15:20 UTC by LunrEclipse

Fixes issue of Token Rich Link Previews background color being too white from color extraction by adding an additional check at the end to check distance from [255, 255, 255] and dimming accordingly.

Before:
![0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2-1](https://github.com/Uniswap/interface/assets/35351983/ff18c299-1329-48f7-80af-95ee0d205edd)

After:
![0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2](https://github.com/Uniswap/interface/assets/35351983/f5d70293-6750-4329-99d5-121e7020b4d6)

2023-08-14 22:55 UTC, zzmp requested changes

2023-08-14 22:55 UTC, zzmp commented on functions/utils/getColor.ts
> +  }
Should this be a while loop to enforce that distance ends up >=50?
Should there be a check that r,g,b > 0?

```suggestion
  if (checkDistance) {
    let distance = Math.sqrt((r - 255)**2, (g - 255)**2, (b - 255)**2)
    while (distance < 50) {
      r = Math.max(r - 20, 0)
      g = Math.max(g - 20, 0)
      b = Math.max(b - 20, 0)
      distance = Math.sqrt((r - 255)**2, (g - 255)**2, (b - 255)**2)
    }
  }
```

2023-08-15 15:28 UTC, zzmp approved these changes

2023-08-17 15:25 UTC, JFrankfurt commented
The after image is still super low contrast--can we add something like readableColor to this?

https://polished.js.org/docs/#readablecolor

2023-08-17 15:38 UTC, LunrEclipse commented
> The after image is still super low contrast--can we add something like readableColor to this?
> 
> https://polished.js.org/docs/#readablecolor

After some tweaking this is what it currently looks like. Is the contrast still too low?
<img width="1078" alt="Screenshot 2023-08-17 at 11 37 49 AM" src="https://github.com/Uniswap/interface/assets/35351983/83ff626d-6b0a-4f2e-a1a5-da6beddd6947">

2023-08-17 16:06 UTC, JFrankfurt commented
I prefer the second option, but I think it would be best to still draw the color from the token logo and use `readableColor` to render black/white text based on contrast.

2023-08-17 17:15 UTC, JFrankfurt approved these changes

2023-08-17 17:17 UTC, JFrankfurt approved these changes

2023-08-17 17:30 UTC, merged