fix: zustand, migrate to createWithEqualityFn
Uniswap/interface pull request #7220
Opened 2023-08-23 22:21 UTC by just-toby

## Description

using an equality function in the zustand accessor is now deprecated. the migration is to replace `create` with `createWithEqualityFn` and pass the same `shallow` comparator we were using before.

_Relevant docs:_ https://github.com/pmndrs/zustand/discussions/1937

## Screen capture

warnings in the console

### After

no warnings in the console

## Test plan

let e2e tests run

2023-08-23 22:24 UTC, JackShort commented on src/pages/Swap/index.tsx
> +    console.log('handleContinueToReview', trade)
i don't think this should be in here?

2023-08-23 22:26 UTC, just-toby commented on src/pages/Swap/index.tsx
> +    console.log('handleContinueToReview', trade)
what the heck!

2023-08-24 19:07 UTC, JackShort approved these changes

2023-08-24 21:15 UTC, cbachmeier requested changes

2023-08-24 21:15 UTC, cbachmeier commented on src/nft/components/profile/list/Modal/ListModal.tsx
> -      shallow
I'm getting a bug with the listing experience where when I have a collection that needs to be approved, the tx auto completes and goes back to the profile page. This isn't happening on main or staging
this branch:
![listForSale](https://github.com/Uniswap/interface/assets/11512321/10a2cea8-bd6e-4133-92a1-e85f6f84e4dd)
staging:
![listForSaleStaging](https://github.com/Uniswap/interface/assets/11512321/01933b57-8dbc-4caa-b601-f6b2073d9eba)

2023-09-11 23:05 UTC, cbachmeier approved these changes

2023-09-11 23:06 UTC, merged