feat: uniswapX default feature flag
Uniswap/interface pull request #7246
Opened 2023-08-30 16:48 UTC by just-toby

## Description

_Linear ticket:_
_Slack thread:_
_Relevant docs:_

## Screen capture

### Before
|    Mobile    |   Desktop    |
| ------------ | ------------ |
| paste_before | paste_before |

### After
|    Mobile    |   Desktop   |
| ------------ | ----------- |
| paste_after  | paste_after |

## Test plan

### Reproducing the error

1. 

### QA (ie manual testing)

- [ ] N/A

#### Devices

### Automated testing

- [ ] Unit test
- [ ] Integration/E2E test

2023-09-06 15:52 UTC, cbachmeier reviewed
If I have the flag on and then I toggle on and off local routing, should X not be back on?
![flagDefaultXLocal](https://github.com/Uniswap/interface/assets/11512321/4f5dd7f5-a669-4d92-b460-d7957cbb7cc9)

2023-09-06 16:02 UTC, cbachmeier requested changes

2023-09-06 16:02 UTC, cbachmeier commented on src/state/routing/utils.ts
> +  if (isUniswapXBetter && (args.routerPreference === RouterPreference.X || args.isUniswapXDefaultEnabled)) {
```suggestion
  if (isUniswapXBetter && (routerPreference === RouterPreference.X || isUniswapXDefaultEnabled)) {
```

2023-09-06 18:01 UTC, JackShort approved these changes

2023-09-06 20:40 UTC, cbachmeier commented
> yes, good catch. i needed to add a case for RouterPreference.CLIENT. thanks!

@just-toby still getting this same behaviour on the latest deploy

2023-09-07 19:39 UTC, cbachmeier approved these changes

2023-09-07 19:41 UTC, just-toby commented on src/pages/Swap/index.tsx
> +      {!showOptInSmall && !isUniswapXDefaultEnabled && <UniswapXOptIn isSmall={false} swapInfo={swapInfo} />}
i think it would be confusing since we have two different lines using `showOptInSmall` in different ways (see L803 below)

2023-09-07 19:43 UTC, JackShort approved these changes

2023-09-07 19:52 UTC, merged