fix: ci added CODEOWNERS github format
Uniswap/interface pull request #7285
Opened 2023-09-08 19:25 UTC by natew

## Description

_Linear ticket:_
_Slack thread:_
_Relevant docs:_

## Screen capture

### Before
|    Mobile    |   Desktop    |
| ------------ | ------------ |
| paste_before | paste_before |

### After
|    Mobile    |   Desktop   |
| ------------ | ----------- |
| paste_after  | paste_after |

## Test plan

### Reproducing the error

1. 

### QA (ie manual testing)

- [ ] N/A

#### Devices

### Automated testing

- [ ] Unit test
- [ ] Integration/E2E test

2023-09-08 19:26 UTC, zzmp requested changes

2023-09-08 19:26 UTC, zzmp commented on .github/workflows/1-main-to-staging.yml
> +          echo '* @uniswap/web-reviewers' > CODEOWNERS
This should still be admins, not reviewers, as we want tighter controls on the `releases/*` branches.
```suggestion
          echo '* @uniswap/web-admins' > CODEOWNERS
```

2023-09-12 17:09 UTC, natew commented
@zzmp updated

2023-09-12 17:26 UTC, zzmp approved these changes

2023-09-14 17:27 UTC, just-toby approved these changes

2023-09-14 17:59 UTC, merged