fix: Use current network name in Gas Breakdown tooltip
Uniswap/interface pull request #7292
Opened 2023-09-10 15:10 UTC by darkwing

## Description
Fixes the GassBreakdownTooltip to use the current network name instead of the hardcoded "Ethereum network" text

## Screen capture

### Before
|    Mobile    |   Desktop    |
| ------------ | ------------ |
| paste_before | paste_before |

### After
|    Mobile    |   Desktop   |
| ------------ | ----------- |
| paste_after  | paste_after |
<img width="652" alt="SCR-20230910-jgkq" src="https://github.com/Uniswap/interface/assets/46655/c15f9621-f80a-4b8a-966a-372c8b815d94">

## Test plan

### Reproducing the error

1. Switch to any non-EthereumMainnet network
2. Go to Swaps
3. Select "to" and "from" tokens
4. Wait for the the gas estimate icon to display
5. Hover of the gas estimate icon to see the GasBreakdownTooltip
6. Ensure that the network name matches the current network

### QA (ie manual testing)

- [ ] N/A

#### Devices

### Automated testing

- [ ] Unit test
- [ ] Integration/E2E test

2023-09-11 17:20 UTC, tinaszheng requested changes

2023-09-11 17:20 UTC, tinaszheng commented on src/components/swap/GasBreakdownTooltip.tsx
> +  const { chainId } = useWeb3React()
the Swap component's chainId can technically be different than the user's connected chainId

use `trade.inputAmount.currency.chainId` instead

2023-09-18 22:43 UTC, natew approved these changes

2023-09-29 18:55 UTC, just-toby approved these changes

2023-10-04 21:40 UTC, just-toby commented
this is a duplicate of #6979 but we'll probably merge whichever one updates first

2023-10-04 21:40 UTC, just-toby commented
@darkwing can you rebase and fix conflicts?

2023-10-12 01:49 UTC, darkwing commented
Updated as requested!

2025-04-24 12:36 UTC, closed without merging