fix: fetch balances when opening token selector in LP page
Uniswap/interface pull request #7321
Opened 2023-09-15 21:12 UTC by just-toby

## Description

we're not properly fetching the user's token balances on the LP page. this should happen when hovering over the token input similar to the swap component.

to fix we just want to wrap the token input with a `PrefetchBalancesWrapper` which triggers the fetch

_Slack thread:_ https://uniswapteam.slack.com/archives/C04D07TQBT4/p1694811755326329

## Test plan

### Reproducing the error

1. go to add liquidity, v2 or v3 - notice that the token balances don't load when you open the selector

### QA (ie manual testing)

- [x] repeat step 1 above but notice that the balances load now

2023-09-15 21:12 UTC, just-toby commented on src/components/CurrencyInputPanel/index.tsx
> +              <PrefetchBalancesWrapper shouldFetchOnAccountUpdate={modalOpen}>
just wrapping with this

2023-09-15 23:26 UTC, JFrankfurt requested changes
lgtm--1 request

2023-09-15 23:26 UTC, JFrankfurt commented on src/components/CurrencyInputPanel/index.tsx
> +import PrefetchBalancesWrapper from 'components/AccountDrawer/PrefetchBalancesWrapper'
path name might lead people to believe this is exclusively an account component--should prob bump it up to a root level component now that it's used here

2023-09-15 23:46 UTC, natew approved these changes
agree w @JFrankfurt otherwise lgtm

2023-09-18 20:18 UTC, JFrankfurt approved these changes

2023-09-18 21:49 UTC, merged