feat: show usd price with no input amount
Uniswap/interface pull request #7328
Opened 2023-09-18 17:15 UTC by just-toby

## Description

fixes #1712 by defaulting to an input amount of "1" when calculating the USD value

_Linear ticket:_ https://github.com/Uniswap/interface/issues/1712

## Screen capture

### Before
<img width="521" alt="image" src="https://github.com/Uniswap/interface/assets/66155195/96f45668-fcc3-4482-9200-594a3d760199">

### After

<img width="521" alt="image" src="https://github.com/Uniswap/interface/assets/66155195/fd817d84-9c0a-4c03-aced-a0476cb5a7de">

## Test plan

<img width="521" alt="Screenshot 2023-09-18 at 10 11 57 AM" src="https://github.com/Uniswap/interface/assets/66155195/79f3662e-48b8-489b-a03a-abb1d019ec41">

2023-09-18 22:44 UTC, natew commented on src/pages/Swap/index.tsx
> +    currencies[Field.INPUT] ?? undefined
`?? undefined` i think that can just be removed

2023-09-18 22:45 UTC, natew commented on src/pages/Swap/index.tsx
> +    currencies[Field.INPUT] ?? undefined
unless currencies can return `null` and it only wants an undefined type there which would be odd

2023-09-18 22:45 UTC, natew requested changes
see comment

2023-09-19 01:40 UTC, JFrankfurt commented on src/pages/Swap/index.tsx
> +  )
this is muuuuch harder to parse quickly. Can you find a more readable way to break out the same logic?

2023-09-19 18:15 UTC, JFrankfurt approved these changes

2023-09-20 21:14 UTC, natew commented on src/state/swap/hooks.tsx
> +  currencies: { [field in Field]?: Currency | undefined }
`?:` already means `| undefined` so no need for `| undefined`

2023-09-20 21:14 UTC, natew commented on src/lib/hooks/useCurrency.ts
> +  if (currencyId === null || currencyId === undefined || !isSupportedChain(chainId)) return undefined
can just `return` as it returns undefined

2023-09-20 21:14 UTC, natew requested changes
small changes

2023-09-22 17:30 UTC, cbachmeier approved these changes

2023-09-22 17:31 UTC, merged