fix: preconnect
Uniswap/interface pull request #7340
Opened 2023-09-18 23:44 UTC by zzmp

## Description

Updates preconnect to the bare subdomains for `api.uniswap.org` and `mainnet.infura.io`, to more quickly load quotes once requested.

2023-09-19 19:16 UTC, just-toby requested changes

2023-09-19 19:16 UTC, just-toby commented on public/index.html
> -    <link rel="preconnect" href="%REACT_APP_AMPLITUDE_PROXY_URL%" />
why remove amplitude though?

2023-09-19 19:16 UTC, just-toby commented on public/index.html
> -    <link rel="preconnect" href="%REACT_APP_AMPLITUDE_PROXY_URL%" />
nevermind, i see that the proxy live at the same domain+subdomain as the quote API

2023-09-19 19:17 UTC, just-toby commented on public/index.html
> -    <link rel="preconnect" href="%REACT_APP_AMPLITUDE_PROXY_URL%" />
maybe comment that is intended to catch  quotes, proxies etc under the umbrella

2023-09-19 19:17 UTC, just-toby approved these changes

2023-09-20 19:17 UTC, natew approved these changes

2023-09-20 19:30 UTC, merged