fix: unhide native gas token from miniportfolio
Uniswap/interface pull request #7374
Opened 2023-09-25 15:45 UTC by kristiehuang

Mini-portfolio should display native gas tokens even if balance is <$1

Linear ticket: https://linear.app/uniswap/issue/WEB-2876/make-gas-tokens-default-not-hidden-on-web-even-if-under-dollar1

## Screen capture

### Before
|    Mobile    |   Desktop    |
| ------------ | ------------ |
| paste_before | paste_before |

### After
|    Mobile    |   Desktop   |
| ------------ | ----------- |
| paste_after  | paste_after |

## Test plan

### Reproducing the error

1. 

### QA (ie manual testing)

- [ ] N/A

#### Devices

### Automated testing

- [ ] Unit test
- [ ] Integration/E2E test

2023-09-28 17:17 UTC, tinaszheng requested changes

2023-09-28 17:17 UTC, tinaszheng commented on src/utils/splitHiddenTokens.tsx
>        // if undefined we keep visible (see https://linear.app/uniswap/issue/WEB-1940/[mp]-update-how-we-handle-what-goes-in-hidden-token-section-of-mini)
i think this comment should go above line 15 now? or else the line break here is very awk

2023-09-28 17:17 UTC, tinaszheng commented on src/utils/splitHiddenTokens.tsx
> +      !(tokenBalance.token?.standard == TokenStandard.Native) // do not hide native tokens regardless of small balance
```suggestion
      tokenBalance.token?.standard !== TokenStandard.Native // do not hide native tokens regardless of small balance
```

2023-09-28 17:35 UTC, tinaszheng approved these changes

2023-10-04 22:06 UTC, cbachmeier approved these changes

2023-10-04 22:07 UTC, just-toby approved these changes
lgtm

2023-10-05 16:03 UTC, mattbspector approved these changes

2023-10-05 19:28 UTC, tinaszheng approved these changes

2023-10-05 19:49 UTC, tinaszheng approved these changes

2023-10-06 16:11 UTC, merged