fix: add unit test
Uniswap/interface pull request #7384
Opened 2023-09-27 22:50 UTC by just-toby

## Description

fix activity parsing for wrap/unwrap transactions that are labelled as "LEND" by zerion

_Linear ticket:_ https://linear.app/uniswap/issue/WEB-2721/[web][metamask]-inaccurate-title-and-transaction-hash-paragraph-in

## Screen capture

### Before

<img width="559" alt="Screenshot 2023-09-27 at 3 39 09 PM" src="https://github.com/Uniswap/interface/assets/66155195/3902698c-f8c6-4382-951a-e7302e07b137">

### After

<img width="559" alt="Screenshot 2023-09-27 at 3 38 47 PM" src="https://github.com/Uniswap/interface/assets/66155195/a573ce28-d804-4149-9a1b-cd3d84ffe41e">

## Test plan

### Reproducing the error

1. wrap ETH or unwrap WETH, let the transaction confirm, then open the Mini Portfolio activity history and see "LEND"

### QA (ie manual testing)

- [x] repeat above process, verify that "wrapped" or "unwrapped" is shown instead w/ amounts

### Automated testing

- [x] Unit test

2023-09-28 14:33 UTC, justindomingue commented
could this be a backend fix?

2023-09-28 15:19 UTC, cartcrom requested changes

2023-09-28 15:19 UTC, cartcrom commented on src/components/AccountDrawer/MiniPortfolio/Activity/parseRemote.tsx
> +}
reuse swap logic:
```suggestion
/**
 * Some unrap/unwrap transactions are erroneously labelled as lend transactions on the backend.
 * This function parses the transaction changes to determine if the transaction is a wrap/unwrap transaction.
 */
function parseLend(changes: TransactionChanges, formatNumberOrString: FormatNumberOrStringFunctionType) {
  const native = changes.TokenTransfer.find((t) => t.tokenStandard === 'NATIVE')?.asset
  const erc20 = changes.TokenTransfer.find((t) => t.tokenStandard === 'ERC20')?.asset

  if (native && erc20 && gqlToCurrency(native)?.wrapped.address === gqlToCurrency(erc20)?.wrapped.address) {
    return parseSwap(changes, formatNumberOrString)
  }

  return { title: t`Unknown Lend` }
}
```

2023-09-28 18:47 UTC, just-toby commented
> could this be a backend fix?

i think this is coming from zerion - i can notify the backend team just in case this is not desired behavior. but don't see a reason why we shouldn't update this logic in the meantime.

i was also torn on this because i think wrapping is technically lending

2023-09-28 22:17 UTC, natew approved these changes

2023-09-29 14:59 UTC, cartcrom approved these changes

2023-09-29 15:01 UTC, cartcrom commented
> > could this be a backend fix?
> 
> i think this is coming from zerion - i can notify the backend team just in case this is not desired behavior. but don't see a reason why we shouldn't update this logic in the meantime.
> 
> i was also torn on this because i think wrapping is technically lending

I have reported this to BE, it should be fixed on either zerion or the BE's end eventually because we're _sometimes_ getting SWAP and other times getting LEND

2023-09-29 17:26 UTC, merged