fix: rename WrappedTokenInfo class
Uniswap/interface pull request #7495
Opened 2023-10-18 22:33 UTC by kristiehuang

Misleading class name, thought it was for WETH/WBTC/etc. Proposing a rename to TokenInfoWrapper?

Moved the class out of `src/state/lists` into `utils` since it isn't only used for Redux tokenlists, it is also used to wrap Gql query Tokens

## Description

_Linear ticket:_
_Slack thread:_
_Relevant docs:_

## Screen capture

### Before
|    Mobile    |   Desktop    |
| ------------ | ------------ |
| paste_before | paste_before |

### After
|    Mobile    |   Desktop   |
| ------------ | ----------- |
| paste_after  | paste_after |

## Test plan

### Reproducing the error

1. 

### QA (ie manual testing)

- [ ] N/A

#### Devices

### Automated testing

- [ ] Unit test
- [ ] Integration/E2E test

2023-10-19 18:23 UTC, cartcrom requested changes

2023-10-19 18:23 UTC, cartcrom commented on src/nft/components/profile/list/NFTListRow.tsx
> +const TokenFromList = styled(Column)`
I think this one is accidental

2023-10-19 18:41 UTC, kristiehuang commented on src/nft/components/profile/list/NFTListRow.tsx
> +const TokenFromList = styled(Column)`
oops good catch thank you

2023-10-19 18:51 UTC, cartcrom approved these changes

2023-10-19 19:09 UTC, mattbspector approved these changes

2023-11-06 18:32 UTC, cartcrom approved these changes

2023-11-06 21:15 UTC, merged