fix: remove version check lists update
Uniswap/interface pull request #7544
Opened 2023-11-02 20:52 UTC by kristiehuang

## Description

_Linear ticket:_
_Slack thread:_
_Relevant docs:_

## Screen capture

### Before
|    Mobile    |   Desktop    |
| ------------ | ------------ |
| paste_before | paste_before |

### After
|    Mobile    |   Desktop   |
| ------------ | ----------- |
| paste_after  | paste_after |

## Test plan

### Reproducing the error

1. 

### QA (ie manual testing)

- [ ] N/A

#### Devices

### Automated testing

- [ ] Unit test
- [ ] Integration/E2E test

2023-11-02 22:32 UTC, zzmp requested changes

2023-11-02 22:32 UTC, zzmp commented on src/state/migrations/3.ts
> +    const tokenAddresses: { [key in ChainId]?: string } = {
```suggestion
    const USDCe_ADDRESSES: { [key in ChainId]?: string } = {
```

2023-11-02 22:32 UTC, zzmp commented on src/state/migrations/3.ts
> +    const tokenAddresses: { [key in ChainId]?: string } = {
Group your logic, and add comments describing what is happening:

```
let tokens ...

// Update USDC.e tokens to use the the new USDC.e symbol (from USDC)
...

// Update USDbC token to use the new USDbC symbol (from USDC)
...

return {
...
}

2023-11-02 22:32 UTC, zzmp commented on src/state/migrations/3.ts
> +    let tokens = { ...state.user.tokens }
This can be mutable, no? Why not just mutate it, and then always return state?

2023-11-06 18:11 UTC, mattbspector approved these changes

2023-11-06 18:23 UTC, cartcrom approved these changes
LGTM. hope we can gut most of this tokenlist code soon

2023-11-06 18:27 UTC, zzmp approved these changes

2023-11-06 19:20 UTC, merged