fix: reset token selections when  changing chains on /add
Uniswap/interface pull request #7561
Opened 2023-11-10 00:36 UTC by just-toby

## Description

fixes an issue on the `/add` page where token selections from the previous chain persist to the new chain, and are displayed as "UNKNOWN" ...

my fix here is to disallow any "unknown" tokens since they likely don't exist. an "unknown" token is one where we couldn't get valid decimals/name/symbol from the onchain call.

the token state on this page is actually managed via the URL route and is actually hard to change. (i tried using react router to reset the state in many different ways, but couldn't get it working). 
we might want to consider moving away from URL-based state management on this page at some point, but i wanted to submit this simpler fix as a short term solution.

_Linear ticket:_ https://linear.app/uniswap/issue/WEB-3014/if-you-change-network-in-create-position-it-doesnt-clear-input
_Slack thread:_
_Relevant docs:_

## Screen capture

### Before

https://github.com/Uniswap/interface/assets/66155195/4593daaa-fb4b-47a9-89b3-bf39f929eef2

### After

https://github.com/Uniswap/interface/assets/66155195/9415c53c-3c7c-4c8f-b183-7db3825c1a2d

## Test plan

### Reproducing the error

1. go to /add/ETH page
2. select tokens
3. change chain
4. notice that the tokens are "unknown" on new chain

2023-11-10 15:48 UTC, JFrankfurt commented
Can you add an e2e test that handles this case?

2023-11-10 15:48 UTC, JFrankfurt approved these changes

2023-11-10 15:49 UTC, JFrankfurt commented on src/lib/hooks/useCurrency.ts
> +    }
might be a good time to add a `useCurrency.test.ts`

2023-11-13 16:46 UTC, mattbspector approved these changes

2023-11-13 20:21 UTC, JFrankfurt approved these changes

2023-11-13 20:21 UTC, JFrankfurt requested changes

2023-11-13 20:21 UTC, JFrankfurt commented on cypress/e2e/add-liquidity.test.ts
> +  it.only('clears the token selection when chain changes', () => {
```suggestion
  it('clears the token selection when chain changes', () => {
```

2023-11-13 20:53 UTC, just-toby commented on cypress/e2e/add-liquidity.test.ts
> +  it.only('clears the token selection when chain changes', () => {
dang

2023-11-13 21:09 UTC, JFrankfurt approved these changes

2023-11-13 23:10 UTC, merged